const shopActionTypes = {
  REQUEST_COLLECTIONS_START: 'REQUEST_COLLECTIONS_START',
  REQUEST_COLLECTIONS_SUCCESS: 'REQUEST_COLLECTIONS_SUCCESS',
  REQUEST_COLLECTIONS_FAILED: 'REQUEST_COLLECTIONS_FAILED'
}

export default shopActionTypes;
