const ordersActionTypes = {
  UPDATE_ORDER_IN_FIREBASE: 'UPDATE_ORDER_IN_FIREBASE',
  REQUEST_ORDERS_START: 'REQUEST_ORDERS_START',
  REQUEST_ORDERS_SUCCESS: 'REQUEST_ORDERS_SUCCESS',
  REQUEST_ORDERS_FAILED: 'REQUEST_ORDERS_FAILED',
  CLEAR_ORDERS: 'CLEAR_ORDERS',
  SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
  UNSET_CURRENT_ORDER: 'UNSET_CURRENT_ORDER'
};

export default ordersActionTypes;
